name: "Void Linux"
on:
  schedule:
    - cron: "0 13 * * 1"
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64-musl", "armv7l-musl", "x86_64-musl"]
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: get date tag
      run: curl https://repo-default.voidlinux.org/live/current/ | tr '"' ' '  | grep href | awk '{print $3}' | tr '-' ' ' | awk '{print $NF}' | grep ".xz" | tr '.' ' ' | awk '{print $1}' | head -n 1 > date_id
    - name: Get date tag
      id: date_id
      run: echo "date_id=$(cat date_id)" >> $GITHUB_ENV
    - name: create docker image
      run: |
        docker import --change 'CMD /bin/bash' https://repo-default.voidlinux.org/live/current/void-${{ matrix.arch }}-ROOTFS-${{ env.date_id }}.tar.xz ${{ secrets.DOCKER_USERNAME }}/void:${{ matrix.arch }}-${{ env.date_id }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/void:${{ matrix.arch }}-${{ env.date_id }} ${{ secrets.DOCKER_USERNAME }}/void:${{ matrix.arch }}-latest
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push to docker (dated)
      run: docker push ${{ secrets.DOCKER_USERNAME }}/void:${{ matrix.arch }}-${{ env.date_id }}
    - name: push to docker (latest)
      run: docker push ${{ secrets.DOCKER_USERNAME }}/void:${{ matrix.arch }}-latest
    
